mails_mail_mailsent_detail:
    path:      /mailsent/{id}
    defaults: { _controller: MailsMailBundle:Mail:viewMailsent }
    requirements:
        id: \d+
        
mails_mail_mailreceived_detail:
    path:      /mailreceived/{id}
    defaults: { _controller: MailsMailBundle:Mail:viewMailreceived }
    requirements:
        page: \d+

mails_mail_mailsent:
    path:     /sent/{page}
    defaults: { _controller: MailsMailBundle:Mail:indexMailsent, page: 1 }
    requirements:
        page: \d*
        
mails_mail_mailreceived:
    path:     /received/{page}
    defaults: { _controller: MailsMailBundle:Mail:indexMailreceived, page: 1 }
    requirements:
        page: \d*

mails_mail_mailreceived_add:
    path:     /mailreceived/add/
    defaults: { _controller: MailsMailBundle:Mail:addMailreceived }
 
mails_mail_mailreceived_delete:
    path:     /mailreceived/delete/{id}
    defaults: { _controller: MailsMailBundle:Mail:deleteMailreceived }
    requirements:
        id: \d+
  
mails_mail_mailsent_add:
    path:     /mailsent/add/
    defaults: { _controller: MailsMailBundle:Mail:addMailsent }  
       
mails_mail_mailsent_delete:
    path:     /mailsent/delete/{id}
    defaults: { _controller: MailsMailBundle:Mail:deleteMailsent }  
    requirements:
        id: \d+
        
mails_admin_mailsent_registration:
    path:      /register/mailsent/{id}
    defaults: { _controller: MailsMailBundle:Mail:registerMailsent }
    requirements:
        id: \d+
        
mails_admin_mailreceived_registration:
    path:      /register/mailreceived/{id}
    defaults: { _controller: MailsMailBundle:Mail:registerMailreceived }
    requirements:
        id: \d+ 
#----------------------------------------------------------------------------- 
mails_mailreceived_filter:
    path:     /mailreceived/filter
    defaults: { _controller: MailsMailBundle:MailreceivedExtra:filterMailreceived }

mails_mailreceived_filter_user:
    path:     /mailreceived/filter/user/{id}
    defaults: { _controller: MailsMailBundle:MailreceivedExtra:filterMailreceivedByUser }
    requirements:
        id: \d+

mails_mailreceived_filter_actor:
    path:     /mailreceived/filter/contact/{id}
    defaults: { _controller: MailsMailBundle:MailreceivedExtra:filterMailreceivedByInterlocutor }
    requirements:
        id: \d+

mails_all_mailreceived_filter:
    path:     /all/mailreceived/filter/{page}
    defaults: { _controller: MailsMailBundle:MailreceivedExtra:filterAllMailreceived, page: 1 }
    requirements:
        page: \d*

mails_mailreceived_validation:
    path:      /validate/mailreceived/{id}
    defaults: { _controller: MailsMailBundle:MailreceivedExtra:validateMailreceived }
    requirements:
        id: \d+ 
#-------------------------------------------------------------------------------
mails_mailsent_filter:
    path:     /mailsent/filter
    defaults: { _controller: MailsMailBundle:MailsentExtra:filterMailsent }

mails_mailsent_filter_user:
    path:     /mailsent/filter/user/{id}
    defaults: { _controller: MailsMailBundle:MailsentExtra:filterMailsentByUser }
    requirements:
        id: \d+

mails_mailsent_filter_actor:
    path:     /mailsent/filter/contact/{id}
    defaults: { _controller: MailsMailBundle:MailsentExtra:filterMailsentByInterlocutor }
    requirements:
        id: \d+

mails_all_mailsent_filter:
    path:     /all/mailsent/filter/{page}
    defaults: { _controller: MailsMailBundle:MailsentExtra:filterAllMailsent, page: 1 }
    requirements:
        page: \d*

mails_mailsent_validation:
    path:      /validate/mailsent/{id}
    defaults: { _controller: MailsMailBundle:MailsentExtra:validateMailsent }
    requirements:
        id: \d+
    
 
    

    

        


    

    

        