services:
    mails_mail.mail_checker:
        class: Mails\MailBundle\Checker\MailsChecker
        arguments: [@doctrine.orm.entity_manager]
        tags:
            -  { name: twig.extension }

    #twig.extension.actions:
        #class: Mails\MailBundle\Twig\NullExtension
        #tags:
#-  { name: twig.extension }
            
    mails_mail.mail_paginator:
        class: Mails\MailBundle\Paginator\MailsPaginator
        arguments: [@doctrine.orm.entity_manager]
        
    mails_mail.mail_indexor:
        class: Mails\MailBundle\Indexor\MailsIndexor
        arguments: [@doctrine.orm.entity_manager]

    mails_mail.nbpage_calculator:
        class: Mails\MailBundle\Calculator\NbPageCalculator

    mails_mail.mail.model.class:
        class: Mails\MailBundle\Entity\Mail

    mails_mail.eraser:
        class: Mails\MailBundle\Eraser\Eraser
        arguments: [@doctrine.orm.entity_manager]

    mails_mail.mail_creator:
        class: Mails\MailBundle\Creator\MailsCreator
        arguments: [@doctrine.orm.entity_manager, @mails_mail.mail.model.class]

    mails_mail.mail_filter:
        class: Mails\MailBundle\Filter\MailsFilter
        arguments: [@doctrine.orm.entity_manager]
        
    mails_mail.mail_lister:
        class: Mails\MailBundle\Lister\MailsLister
        arguments: [@doctrine.orm.entity_manager]

    mails_mail.mails_handler_data:
        class: Mails\MailBundle\HandlerMailsData\HandlerMailsData
        arguments: [@mails_mail.mail_filter, @session]

    mails_mail.mail_factory:
        class: Mails\MailBundle\Factory\MailFactory
