services:
    mails_mail.mail_checker:
        class: Mails\MailBundle\Checker\MailsChecker
        arguments: [@doctrine.orm.entity_manager]
        tags:
            -  { name: twig.extension }
            
    mails_mail.mail_paginator:
        class: Mails\MailBundle\Paginator\MailsPaginator
        arguments: [@doctrine.orm.entity_manager]
        
    mails_mail.mail_indexor:
        class: Mails\MailBundle\Indexor\MailsIndexor
        arguments: [@doctrine.orm.entity_manager]

    mails_mail.nbpage_calculator:
        class: Mails\MailBundle\Calculator\NbPageCalculator

    mails_mail.mail.model.class:
        class: Mails\MailBundle\Entity\Mail

    mails_mail.eraser:
        class: Mails\MailBundle\Eraser\Eraser
        arguments: [@doctrine.orm.entity_manager]

    mails_mail.mail_creator:
        class: Mails\MailBundle\Creator\MailsCreator
        arguments: [@doctrine.orm.entity_manager, @mails_mail.mail.model.class]


