pre_composer_script: |
    #!/bin/bash

    # Do what you need to setup your project
    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/database_user:.*/database_user: fiderlet/" app/config/parameters.yml
    sed -i -e "s/database_password:.*/database_password: kingston/" app/config/parameters.yml  

global_exclude_dirs:
    - vendor
    - vendors
    - test
    - tests
    - Tests
    - lib/vendor

exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app_*.php
