pre_composer_script: |
    #!/bin/bash

    # Do what you need to setup your project
    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/database_user:.*/database_user: fiderlet/" app/config/parameters.yml
    sed -i -e "s/database_password:.*/database_password: kingston/" app/config/parameters.yml  
    sed -i -e "s/database_driver:.*/database_driver: pdo_mysql/"\n   server_version: 5.6/g' -i app/config/config.yml

global_exclude_dirs:
    - vendor
    - vendors
    - test
    - tests
    - Tests
    - lib/vendor

exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app_*.php

rules:
    composer.apc_class_loader_should_be_enabled:
        enabled: true
    composer.dependencies_not_installable:
        enabled: true
    composer.invalid_file:
        enabled: true
    composer.outdated_lock_file:
        enabled: true
    composer.security_issue_in_composer:
        enabled: true
    composer.unfixed_dependency_version:
        enabled: true
    composer.warning:
        enabled: true
    doctrine.database_query_contains_string_and_variable_concatenation:
        enabled: true
    doctrine.invalid_schema:
        enabled: true
    doctrine.use_flush_in_loop:
        enabled: true
    symfony.application_not_bootable:
        enabled: true