pre_composer_script: |
    #!/bin/bash

    # Do what you need to setup your project
    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/database_user:.*/database_user: fiderlet/" app/config/parameters.yml
    sed -i -e "s/database_password:.*/database_password: kingston/" app/config/parameters.yml  

post_composer_script: |
    #!/bin/bash

    # Do what you need to configure your project
    php app/console doctrine:database:create --no-interaction
    php app/console doctrine:schema:create --no-interaction

global_exclude_dirs:
    - vendor
    - vendors
    - test
    - tests
    - Tests
    - lib/vendor
    
exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app_*.php
    - web/app.php
    - web/lib/bootstrap
    - src/Mails/ContactBundle/DependencyInjection
    - src/Mails/MailBundle/DependencyInjection
    - src/Mails/UserBundle/DependencyInjection

rules:
    twig.template_too_complex:
        enabled: true
        max_depth: 5
