<?php

namespace Mails\MailBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends EntityRepository
{
}
