<?php

namespace Mails\MailBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends EntityRepository
{
    public function getContactCompany($adminCompany)
    {
        //Permet de récupérer la liste des contacts de l'entreprise de l'administrateur courant

        $qb = $this
            ->createQueryBuilder('a')
            ->join('a.user', 'u')
            ->addSelect('u')
            ->where('u.company = :company')
            ->setParameter('company', $adminCompany)
        ;

        $query = $qb
                ->getQuery()
                //->useQueryCache(true)
                //->useResultCache(true, 3600, 'find_latest_mailsent')
        ;

        return $query->getResult();
    }
}
