<?php

namespace Mails\MailBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * MailReceivedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailReceivedRepository extends EntityRepository
{  
}
