imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name:                 WebsiteID
        
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        '%kernel.root_dir%/../src/Mails/UserBundle/Resources/views/User/Show': show_users_views
        '%kernel.root_dir%/../src/Mails/UserBundle/Resources/views/User/Mails/MailSent': user_mailsent_views
        '%kernel.root_dir%/../src/Mails/UserBundle/Resources/views/User/Mails/MailReceived': user_mailreceived_views
        '%kernel.root_dir%/../src/Mails/UserBundle/Resources/views/User/Mails/Admin/MailSent': admin_user_mailsent_views
        '%kernel.root_dir%/../src/Mails/UserBundle/Resources/views/User/Mails/Admin/MailReceived': admin_user_mailreceived_views
        '%kernel.root_dir%/../src/Mails/ContactBundle/Resources/views/Contact/Show': show_contact_views
        '%kernel.root_dir%/../src/Mails/ContactBundle/Resources/views/Contact/Mails/MailSent': contact_mailsent_views
        '%kernel.root_dir%/../src/Mails/ContactBundle/Resources/views/Contact/Mails/MailReceived': contact_mailreceived_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailSent/FilterUser/Result': user_mailsent_filter_result_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailReceived/FilterUser/Result': user_mailreceived_filter_result_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailReceived/FilterContact/Result': contact_mailreceived_filter_result_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailSent/FilterContact/Result': contact_mailsent_filter_result_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailReceived/Filter/Result': mailreceived_filter_result_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailSent/Filter/Result': mailsent_filter_result_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailReceived/Detail': mailreceived_detail_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailSent/Detail': mailsent_detail_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailReceived/Form': mailreceived_form_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailSent/Form': mailsent_form_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/ShowLatest': show_latest_mails_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/Delete': delete_mails_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailReceived/Index': mailreceived_index_views
        '%kernel.root_dir%/../src/Mails/MailBundle/Resources/views/Mail/MailSent/Index': mailsent_index_views
    #globals:
        #mails: "@mails_mail.mail_checker"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default

        connections:
            # A collection of different named connections (e.g. default, conn2, etc)
            default:
                dbname:               "%database_name%"
                host:                 "%database_host%"
                port:                 "%database_port%"
                user:                 "%database_user%"
                password:             "%database_password%"
                charset:              UTF8
                driver:               pdo_mysql
                server_version:       5.6

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        #query_cache_driver: memcache
        #result_cache_driver: memcache

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS Configuration   
fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Mails\UserBundle\Entity\User # La classe de l'entité User que nous utilisons

# SFE Configuration
sensio_framework_extra:
    router:      { annotations: true }
    request:     { converters: true, auto_convert: true }
    view:        { annotations: true }
    cache:       { annotations: true }
    security:    { annotations: true }
    psr_message: { enabled: false } # Defaults to true if the PSR-7 bridge is installed

#lsw_memcache:
 #   session:
  #      pool: default
   #     auto_load: true
    #    prefix: "session_"
     #   ttl: 7200
      #  locking: true
       # spin_lock_wait: 150000

    #doctrine:
     #   metadata_cache:
      #      pool: default
       #     entity_manager: default          # the name of your entity_manager connection
        #    document_manager: default
        #result_cache:
         #   pool: default
          #  entity_manager: [default, read]  # you may specify multiple entity_managers
           # prefix: "result_"                # you may specify a prefix for the entries
        #query_cache:
         #   pool: default
          #  entity_manager: default

    #pools:
     #   default:
      #      servers:
       #       - { host: localhost, tcp_port: 11211 }
