mails_core:
    resource: "@MailsCoreBundle/Resources/config/routing.yml"
  
mails_mail:
    resource: "@MailsMailBundle/Resources/config/routing.yml"
    prefix:   /mail

mails_contact:
    resource: "@MailsContactBundle/Resources/config/routing.yml"
    prefix:   /contact

mails_user:
    resource: "@MailsUserBundle/Resources/config/routing.yml"
    prefix:   /user
    
#login:
    #pattern:   /login
    #defaults:  { _controller: MailsUserBundle:Security:login }

#login_check:
    #pattern:   /login_check

#logout:
    #pattern:   /logout
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    