mails_core_home:
    path:     /
    methods: [ get ]
    defaults: { _controller: MailsCoreBundle:Home:index }
    
mails_core_contact:
    path:     /contact
    methods: [ get,post ]
    defaults: { _controller: MailsCoreBundle:Home:contact }

mails_core_company:
    path:     /company
    methods: [ get,post ]
    defaults: { _controller: MailsCoreBundle:Home:createCompany }

mails_core_company_infos:
    path:     /infos/company
    methods: [ get ]
    defaults: { _controller: MailsCoreBundle:Home:infosCompanyLayout }

mails_core_workspace_admin:
    path:     /workspace/admin
    methods: [ get ]
    defaults: { _controller: MailsMailBundle:Mail:showLatestNotValidatedMailByUser }

mails_core_workspace_secretary:
    path:     /workspace/secretary
    methods: [ get ]
    defaults: { _controller: MailsMailBundle:Mail:showLatestUnregistredMailToSecretary }
