mails_core_home:
    path:     /
    defaults: { _controller: MailsCoreBundle:Home:index }
    
mails_core_contact:
    path:     /contact
    defaults: { _controller: MailsCoreBundle:Home:contact }
    
